### ISSUE TITLE
Isn't 8K features too much?

### ISSUE THREAD

**Issue by vladimirkovacevic** [cypher93/genomska_informatika#2]
Having in mind that we have a few hundreds of samples 8K features looks too much to obtain a model that generalizes well. Maybe you can try giving SelectKBest a lower number of features?

**Comment by cypher93** [comment]
Actually, I've tried several values of K, before settling on 8k.

I started out with a low value of 100 features and increased it progressively. That's when I noticed that the RMSE of the best performing model (on the training data) peaks somewhere between 2K and 10K.

After seeing that the models have this behavior, and concluding that the performance difference is not that big regardless of the selection of K, I stopped investigating further. Also, selecting a high value of K highlights how well Lasso regression handles overfitting on sparse data, although I suspect that all the Linear regressions set at least some weights to ~0 (performing a further "selection" of features).

I've added a graph showing some of these findings. Running these tests took approx. 1-2h in total, so the time penalty on the evaluation process wasn't that big.
