### ISSUE TITLE
Which genes/features carry most importance?

### ISSUE THREAD

**Issue by vladimirkovacevic** [cypher93/genomska_informatika#3]
It would be interesting to find out if the most important genes obtained by ML analysis are related to physiological processes related to pregnancy. Just a thought, no need to go deeply into this.

**Comment by cypher93** [comment]
I grabbed the 10 most interesting genes (according to select best K, where K is at 2000) and added some links describing them.

I've only been able to directly connect 2 to something that might be pregnancy related, although there may be more connections that I wasn't able to spot.

6498_at - SKI like proto-oncogene. This gene regulates cell growth - https://www.ncbi.nlm.nih.gov/gene/?term=6498+at
79087_at - ALG12. Mutations in this gene have been associated with congenital disorder - https://www.ncbi.nlm.nih.gov/gene/?term=79087+at

199675_at - https://www.ncbi.nlm.nih.gov/gene/?term=199675+at
9619_at - https://www.ncbi.nlm.nih.gov/gene/?term=9619+at
2359_at - https://www.genecards.org/cgi-bin/carddisp.pl?gene=FPR3&keywords=FPR3
5169_at - https://www.ncbi.nlm.nih.gov/gene/?term=5169+at
51108_at - https://www.genecards.org/cgi-bin/carddisp.pl?gene=METTL9&keywords=METTL9
6689_at - https://www.ncbi.nlm.nih.gov/gene/?term=6689+at
3507_at - https://www.ncbi.nlm.nih.gov/gene/?term=3507+at
2040_at - https://www.ncbi.nlm.nih.gov/gene/?term=2040+AT

**Comment by vladimirkovacevic** [comment]
Thanks! It would be great to add these to the slides as well.
