### ISSUE TITLE
Different ML models?

### ISSUE THREAD

**Issue by vladimirkovacevic** [cypher93/genomska_informatika#4]
Have you maybe considered different ML models, for example, RandomForest, XGBoost, MultyLayerPerceptron, etc.?

**Comment by cypher93** [comment]
I've tried finding some information on what ML models might perform best on sparse data, but it boils down to what might reduce the number of features... I came across XGBoost and MultiLayerPerceptron, but I wasn't sure what might be the best option, so I stuck with what I knew. The main reason for not going a step further was that I was satisfied with the achieved RMSE using simple linear models (during cross-validation on training data).

I also found this paper early on, which seems to tackle the issue: https://core.ac.uk/reader/232375850.
I haven't dug deeper yet, but for a larger project, it might be interesting to implement.
